# Generated by Django 4.2.16 on 2024-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('logo_path', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('poster_path', models.URLField()),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('tmdb_vote_average', models.FloatField()),
                ('movie_id', models.IntegerField()),
                ('picture_url', models.JSONField(blank=True, null=True)),
                ('video_url', models.JSONField(blank=True, null=True)),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('poster_palette', models.JSONField(blank=True, null=True)),
                ('watchapedia', models.URLField()),
                ('genre_ids', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('watch_providers', models.ManyToManyField(related_name='movies', to='movies.provider')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionColor',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emotions_color', models.JSONField()),
                ('emotion_id', models.ManyToManyField(related_name='emotion_colors', to='movies.emotion')),
                ('genres_id', models.ManyToManyField(related_name='emotion_colors', to='movies.genre')),
            ],
        ),
    ]
